name: CI

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t oguilhermecorreia/webapp:latest .
  
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v3

      - name: Proof HTML
        uses: anishathalye/proof-html@v2.1.2
        with:
          directory: ./
          check_html: true
          check_css: true
        continue-on-error: true

      - name: Run OWASP ZAP SAST scan
        run: docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8083 -J zap_report.json -r zap_report.html || true


  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.USER }}  
          password: ${{ secrets.PASSWD }}

      - name: Build Docker image for deploy
        run: docker build -t oguilhermecorreia/webapp:latest .
          
      - name: Push Docker image to registry
        run: docker push oguilhermecorreia/webapp:latest

